name       : libdvdcss
version    : 1.4.0
release    : 2
source     :
    - http://download.videolan.org/libdvdcss/1.4.0/libdvdcss-1.4.0.tar.bz2 : 2089375984800df29a4817b37f3123c1706723342d6dab4d0a8b75c25c2c845a
homepage   : http://www.videolan.org/index.htm
license    : GPL-2.0
component  : multimedia.library
summary    : DVD decryption library
description: |
    libdvdcss is a simple library designed for accessing DVDs as a block device without having to bother about the decryption.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
