name       : libdvdcss
version    : 1.4.1
release    : 3
source     :
    - https://download.videolan.org/pub/libdvdcss/1.4.1/libdvdcss-1.4.1.tar.bz2 : eb073752b75ae6db3a3ffc9d22f6b585cd024079a2bf8acfa56f47a8fce6eaac
homepage   : https://www.videolan.org/index.htm
license    : GPL-2.0
component  : multimedia.library
summary    : DVD decryption library
description: |
    libdvdcss is a simple library designed for accessing DVDs as a block device without having to bother about the decryption.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install

