name       : libdvdcss
version    : 1.4.3
release    : 7
source     :
    - https://download.videolan.org/pub/libdvdcss/1.4.3/libdvdcss-1.4.3.tar.bz2 : 233cc92f5dc01c5d3a96f5b3582be7d5cee5a35a52d3a08158745d3d86070079
homepage   : https://www.videolan.org/developers/libdvdcss.html
license    : GPL-2.0-or-later
component  : multimedia.library
summary    : DVD decryption library
description: |
    libdvdcss is a simple library designed for accessing DVDs as a block device without having to bother about the decryption.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -fr $installdir/usr/share
