name       : libdvdcss
version    : 1.4.2
release    : 4
source     :
    - https://download.videolan.org/pub/libdvdcss/1.4.2/libdvdcss-1.4.2.tar.bz2 : 78c2ed77ec9c0d8fbed7bf7d3abc82068b8864be494cfad165821377ff3f2575
homepage   : https://www.videolan.org/index.htm
license    : GPL-2.0-or-later
component  : multimedia.library
summary    : DVD decryption library
description: |
    libdvdcss is a simple library designed for accessing DVDs as a block device without having to bother about the decryption.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -fr $installdir/usr/share
